// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package fn

func AnyInt(values []int, check func(int) bool) bool {
	for i := range values {
		if check(values[i]) {
			return true
		}
	}

	return false
}

func AnyInt64(values []int64, check func(int64) bool) bool {
	for i := range values {
		if check(values[i]) {
			return true
		}
	}

	return false
}

func AnyString(values []string, check func(string) bool) bool {
	for i := range values {
		if check(values[i]) {
			return true
		}
	}

	return false
}
