// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package fn

func DivModInt(a, b int) (int, int) {
	return a / b, a % b
}

func DivModInt64(a, b int64) (int64, int64) {
	return a / b, a % b
}
