// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package fn

func MaxInt(values ...int) int {
	var max int

	if len(values) == 0 {
		return max
	} else {
		max = values[0]
	}

	for i := range values {
		if values[i] > max {
			max = values[i]
		}
	}

	return max
}

func MaxInt64(values ...int64) int64 {
	var max int64

	if len(values) == 0 {
		return max
	} else {
		max = values[0]
	}

	for i := range values {
		if values[i] > max {
			max = values[i]
		}
	}

	return max
}

func MaxFloat32(values ...float32) float32 {
	var max float32

	if len(values) == 0 {
		return max
	} else {
		max = values[0]
	}

	for i := range values {
		if values[i] > max {
			max = values[i]
		}
	}

	return max
}

func MaxFloat64(values ...float64) float64 {
	var max float64

	if len(values) == 0 {
		return max
	} else {
		max = values[0]
	}

	for i := range values {
		if values[i] > max {
			max = values[i]
		}
	}

	return max
}
