// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package fn

func MinInt(values ...int) int {
	var min int
	if len(values) == 0 {
		return min
	} else {
		min = values[0]
	}
	for i := range values {
		if values[i] < min {
			min = values[i]
		}
	}
	return min
}

func MinInt64(values ...int64) int64 {
	var min int64
	if len(values) == 0 {
		return min
	} else {
		min = values[0]
	}
	for i := range values {
		if values[i] < min {
			min = values[i]
		}
	}
	return min
}

func MinFloat32(values ...float32) float32 {
	var min float32
	if len(values) == 0 {
		return min
	} else {
		min = values[0]
	}
	for i := range values {
		if values[i] < min {
			min = values[i]
		}
	}
	return min
}

func MinFloat64(values ...float64) float64 {
	var min float64
	if len(values) == 0 {
		return min
	} else {
		min = values[0]
	}
	for i := range values {
		if values[i] < min {
			min = values[i]
		}
	}
	return min
}
