// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package fn

func PowInt(x, y int) int {
	var (
		z int = 1
		i int = 0
	)
	for ; i < y; i++ {
		z = z * x
	}
	return z
}

func PowInt64(x, y int64) int64 {
	var (
		z int64 = 1
		i int64 = 0
	)
	for ; i < y; i++ {
		z = z * x
	}
	return z
}
