// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package fn

func ReduceInt(elements []int, fn func(accm int, curr int) int) int {
	var accm int
	for _, elem := range elements {
		accm = fn(accm, elem)
	}
	return accm
}

func ReduceInt64(elements []int64, fn func(accm int64, curr int64) int64) int64 {
	var accm int64
	for _, elem := range elements {
		accm = fn(accm, elem)
	}
	return accm
}

func ReduceFloat32(elements []float32, fn func(accm float32, curr float32) float32) float32 {
	var accm float32
	for _, elem := range elements {
		accm = fn(accm, elem)
	}
	return accm
}

func ReduceFloat64(elements []float64, fn func(accm float64, curr float64) float64) float64 {
	var accm float64
	for _, elem := range elements {
		accm = fn(accm, elem)
	}
	return accm
}
