// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package fn

func SumInt(values ...int) int {
	return ReduceInt(values, func(accm int, curr int) int { return accm + curr })
}

func SumInt64(values ...int64) int64 {
	return ReduceInt64(values, func(accm int64, curr int64) int64 { return accm + curr })
}

func SumFloat32(values ...float32) float32 {
	return ReduceFloat32(values, func(accm float32, curr float32) float32 { return accm + curr })
}

func SumFloat64(values ...float64) float64 {
	return ReduceFloat64(values, func(accm float64, curr float64) float64 { return accm + curr })
}
